---
driver:
  name: vagrant
  pre_create_command: "cd {{vagrant_root}}/ && vagrant box update"

provisioner:
  name: chef_zero
  log_level: <%= ENV['CHEF_LOG_LEVEL'] || 'auto' %>

verifier:
  name: inspec

platforms:
  - name: gannett/gci-centos7

suites:
  - name: default
    run_list:
      - recipe[php-fpm::test]
    attributes:
      php-fpm:
        pools:
          - name: www
            listen: '127.0.0.1:9001'
